### ISSUE TITLE
unable to load package 'ghc-prim-0.6.1'

### ISSUE THREAD

**Issue by ndr-brt** [tidalcycles/tidal-listener#12]
Installed tidal-listener through `cabal install tidal-listener` (cabal version 3.4.0.0)
Sent a message with a simple `d1 $ s "bd"`
I got back a `/code/error` with this message
```
GHC Exception: unable to load package `ghc-prim-0.6.1'
```

ps: in the tidal-listener console output there are this two errors, don't know if they are releated:
```
tidal-listener: /home/andrea/.ghcup/ghc/8.10.5/lib/ghc-8.10.5/ghci-8.10.5/HSghci-8.10.5.o: unknown symbol `allocateWrite'
tidal-listener: Could not load Object Code /home/andrea/.ghcup/ghc/8.10.5/lib/ghc-8.10.5/ghci-8.10.5/HSghci-8.10.5.o.
```

**Comment by sorki** [comment]
I'm not sure if you can use `install` since `tidal-listener` needs to see Haskell dependencies as it launches interpreter that loads `tidal` and related libraries. You can try launching this with `cabal run` from the repository clone or try setting correct `GHC_PACKAGE_PATH` for installed `tidal-installer` (not sure where it should point).

**Comment by yaxu** [comment]
Ah interesting.. Maybe `cabal v1-install` works though?

**Comment by ndr-brt** [comment]
Same error, with `cabal v1-install` and with `cabal run`

**Comment by yaxu** [comment]
That's strange. Howabout running from ghci, e.g.
```
cd src
ghci
import Sound.Tidal.Listener
listen
```

**Comment by ndr-brt** [comment]
At first I got
```
<no location info>: error:
    Could not load module ‘Sound.Tidal.Listener’
    It is a member of the hidden package ‘tidal-listener-0.1.0.0’.
    You can run ‘:set -package tidal-listener’ to expose it.
    (Note: this unloads all the modules in the current scope.)
```

So I executed
```
:set -package tidal-listener
```

import then worked but when I execute `listen` I get
```
<interactive>:5:1: error: Variable not in scope: listen
```

**Comment by ndr-brt** [comment]
Tried also with cabal 3.2.0.0, same results

**Comment by ndr-brt** [comment]
I think it's related to https://github.com/haskell/haskell-language-server/issues/221
Will read all the comments...

**Comment by yaxu** [comment]
Ah, which distro are you using?

**Comment by sorki** [comment]
Do you use `cabal.project(.local)`?

**Comment by ndr-brt** [comment]
@yaxu ubuntu 21.04.
Tried also with ghc 9.0.1 (I had 8.10.5 installed, because it's recommended by ghcup), same results.
@sorki what do you mean?

**Comment by ndr-brt** [comment]
wait! I don't receive that errors anymore! I think after passing to ghc 9.0.4 (did a lot of trials, can't remember! :joy: )

**Comment by yaxu** [comment]
Hm strange! I guess we close this for now but keep an eye out for this..
