### ISSUE TITLE
Get pattern id into the highlight message

### ISSUE THREAD

**Issue by ndr-brt** [tidalcycles/tidal-listener#15]
At the moment is impossible to associate the pattern with the highlight message, would be nice to insert the pattern id into the `/code/highlight` message

**Comment by sorki** [comment]
See also https://github.com/tidalcycles/tidal-listener/issues/1#issuecomment-829945487

**Comment by yaxu** [comment]
This is fixed in tidal itself: https://github.com/tidalcycles/Tidal/commit/d15a87e1f6fea699ab5e3dc819ea216094356852

**Comment by yaxu** [comment]
Now released as tidal 1.7.8 @ndr-brt
